export const GET_ARTICULOS_REQUEST = "GET_ARTICULOS_REQUEST";
export const GET_ARTICULOS_SUCCESS = "GET_ARTICULOS_SUCCESS";
export const GET_ARTICULOS_FAIL = "GET_ARTICULOS_FAIL";

export const BUILD_ARTICULOS_REQUEST = "BUILD_ARTICULOS_REQUEST";
export const BUILD_ARTICULOS_SUCCESS = "BUILD_ARTICULOS_SUCCESS";
export const BUILD_ARTICULOS_FAIL = "BUILD_ARTICULOS_FAIL";

export const DESTROY_ARTICULOS_REQUEST = "DESTROY_ARTICULOS_REQUEST";
export const DESTROY_ARTICULOS_SUCCESS = "DESTROY_ARTICULOS_SUCCESS";
export const DESTROY_ARTICULOS_FAIL = "DESTROY_ARTICULOS_FAIL";

export const SET_SEARCH_CRITERIA = "SET_SEARCH_CRITERIA";