//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosk.Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int Id { get; set; }
        public string Cantidad { get; set; }
        public string PrecioUnitario { get; set; }
        public int VentaId { get; set; }
        public int FacturaId { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Venta Venta { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
